 version: '2'
 services:
   db:
     image: juank/postgis:9.6-2.4
     hostname: geotrek-postgres
     env_file:
       - docker.env
     volumes:
       - ./private/postgresql:/var/lib/postgresql/data
     ports:
      - "5432:5432"

   redis:
     image: redis:latest
     hostname: geotrek-redis
     env_file:
       - docker.env

   worker:
     build: .
     image: geotrek:2.15.2.dev0
     volumes:
       - ./src:/code/src
       - ./etc:/code/etc
       - ./public:/code/public
     env_file:
       - docker.env
     environment:
       - DJANGO_SETTINGS_MODULE=geotrek.settings.dev
     depends_on:
       - db
       - redis
     working_dir: /code/src
     command: /code/venv/bin/python ./manage.py celery worker -l debug

   convertit:
     hostname: geotrek-convertit
     build:
       context: ./docker/convertit-master
     working_dir: /opt/apps/convertit/
     command: /opt/apps/convertit/bin/pserve development.ini --reload

   screamshotter:
     hostname: geotrek-screamshotter
     depends_on:
       - convertit
     build:
       context: ./docker/screamshotter-master
     command: /opt/apps/screamshotter/bin/python manage.py runserver 0.0.0.0:8001

   django:
     build: .
     image: geotrek:2.15.2.dev0
     hostname: geotrek-django
     tty: true
     volumes:
       - ./src:/code/src
       - ./etc:/code/etc
       - ./public:/code/public
     ports:
       - "8000:8000"
       - "2222:22"
     env_file:
       - docker.env
     user: "1001"
     environment:
       - DJANGO_SETTINGS_MODULE=geotrek.settings.dev
     depends_on:
       - worker
       - screamshotter
     working_dir: /code/src
     command: /code/venv/bin/python ./manage.py runserver_plus 0.0.0.0:8000

